drug_cond = {'FNC' 'B' 'A' 'C'; 'HFK' 'B' 'A' 'C'; 'RPC' 'C' 'A' 'B';...
    'XUE' 'B' 'A' 'C'; 'NDT' 'A' 'B' 'C'; 'QLW' 'C' 'B' 'A'; 'HOG' 'B' 'A' 'C';...
    'CYK' 'C' 'B' 'A'; 'OIQ' 'C' 'A' 'B'; 'UXQ' 'C' 'B' 'A'; 'CMC' 'B' 'C' 'A';...
    'UOC' 'A' 'B' 'C'; 'JPK' 'A' 'C' 'B'; 'TMW' 'B' 'C' 'A'; 'EJG' 'B' 'C' 'A';...
    'CTG' 'C' 'A' 'B'};

hazard_rate_cond = {'FNC' 'B' 'A'; 'HFK' 'A' 'C'; 'RPC' 'A' 'B';...
    'XUE' 'B' 'C'; 'NDT' 'A' 'C'; 'C' 'B' 'A'; 'HOG' 'B' 'A' 'C';...
    'CYK' 'C' 'B' 'A'; 'OIQ' 'C' 'A' 'B'; 'UXQ' 'C' 'B' 'A'; 'CMC' 'B' 'C' 'A';...
    'UOC' 'A' 'B' 'C'; 'JPK' 'A' 'C' 'B'; 'TMW' 'B' 'C' 'A'; 'EJG' 'B' 'C' 'A';...
    'CTG' 'C' 'A' 'B'}